In [1]:
import pandas as pd
import os
from pathlib import Path

In [2]:
project_dir = os.getenv('PROJECT_DIR')
metadata_path = Path(project_dir, 'data/received/metadata/0189_scnRNA_metadata_NA220620.xlsx')
metadata_path

PosixPath('/projects/petar/fgf1/data/received/metadata/0189_scnRNA_metadata_NA220620.xlsx')

In [3]:
meta = pd.read_excel(metadata_path)
meta.head()

/tools/anaconda/envs/nmq407/fgf1/lib/python3.8/site-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

,SCOP ID,Project name,Group Leader,First contact person,Sample name,Sample ID,Organism,Strain,Sex,Tissue,...,Cell line,Cell type,Collection date,Collector,Isolation protocol,Isolation date/pool,Nuclei or Whole cells,Fresh isolated or Frozen nuclei,FACS dye,Comments
0,SCOP_2022_0189,FGF1_ D5_ D14,Tune Pers,Nadia Aalling,M9,NaN,Mus musculus,obob,Male,Mediobasal hypothalamus,...,NaN,NaN,220329,Nadia,Nuclei isolation from frozen brain tissue for ...,22/6/2022,Nuclei,Frozen nuclei,DAPI,Batch 1
1,SCOP_2022_0189,FGF1_ D5_ D14,Tune Pers,Nadia Aalling,M10,NaN,Mus musculus,obob,Male,Mediobasal hypothalamus,...,NaN,NaN,220328,Nadia,Nuclei isolation from frozen brain tissue for ...,23/6/2022,Nuclei,Frozen nuclei,DAPI,Batch 2
2,SCOP_2022_0189,FGF1_ D5_ D14,Tune Pers,Nadia Aalling,M15,NaN,Mus musculus,obob,Male,Mediobasal hypothalamus,...,NaN,NaN,220328,Nadia,Nuclei isolation from frozen brain tissue for ...,24/6/2022,Nuclei,Frozen nuclei,DAPI,Batch 3
3,SCOP_2022_0189,FGF1_ D5_ D14,Tune Pers,Nadia Aalling,N7,NaN,Mus musculus,obob,Male,Mediobasal hypothalamus,...,NaN,NaN,211213,Nadia,Nuclei isolation from frozen brain tissue for ...,22/6/2022,Nuclei,Frozen nuclei,DAPI,Batch 1
4,SCOP_2022_0189,FGF1_ D5_ D14,Tune Pers,Nadia Aalling,N17,NaN,Mus musculus,obob,Male,Mediobasal hypothalamus,...,NaN,NaN,211213,Nadia,Nuclei isolation from frozen brain tissue for ...,23/6/2022,Nuclei,Frozen nuclei,DAPI,Batch 2

In [4]:
keep_cols = ['Sample name', 'Strain', 'Condition 1', 'Condition 2', 'Collection date', 'Isolation date/pool', 'Comments']
meta = meta[keep_cols]
renamed_cols = {name:name.replace(' ', '_').lower() for name in keep_cols}
meta = meta.rename(columns=renamed_cols)
meta = meta.rename(columns={'condition_1': 'treatment',
                            'condition_2': 'time',
                            'isolation_date/pool': 'isolation_date',
                            'comments': 'batch'})
meta.head()

  sample_name strain treatment  time  collection_date isolation_date    batch
0          M9   obob      FGF1  Day5           220329      22/6/2022  Batch 1
1         M10   obob      FGF1  Day5           220328      23/6/2022  Batch 2
2         M15   obob      FGF1  Day5           220328      24/6/2022  Batch 3
3          N7   obob      FGF1  Day5           211213      22/6/2022  Batch 1
4         N17   obob      FGF1  Day5           211213      23/6/2022  Batch 2

In [5]:
collection_replace = {x: "20{}.{}.{}".format(str(x)[0:2], str(x)[2:4], str(x)[4:6]) \
                      for x in meta['collection_date'].unique()}
date_replace = {'22/6/2022': '2022.06.22',
                '23/6/2022': '2022.06.23',
                '24/6/2022': '2022.06.24'}
val_replace = {**collection_replace, **date_replace}
meta.replace(val_replace)

   sample_name strain treatment   time collection_date isolation_date    batch
0           M9   obob      FGF1   Day5      2022.03.29     2022.06.22  Batch 1
1          M10   obob      FGF1   Day5      2022.03.28     2022.06.23  Batch 2
2          M15   obob      FGF1   Day5      2022.03.28     2022.06.24  Batch 3
3           N7   obob      FGF1   Day5      2021.12.13     2022.06.22  Batch 1
4          N17   obob      FGF1   Day5      2021.12.13     2022.06.23  Batch 2
5          N21   obob      FGF1   Day5      2021.12.13     2022.06.24  Batch 3
6          N26   obob      FGF1   Day5      2021.12.13     2022.06.24  Batch 3
7           M8   obob    Veh_PF   Day5      2022.03.29     2022.06.22  Batch 1
8          M11   obob    Veh_PF   Day5      2022.03.29     2022.06.23  Batch 2
9          M14   obob    Veh_PF   Day5      2022.03.29     2022.06.24  Batch 3
10          N8   obob    Veh_PF   Day5      2021.12.14     2022.06.22  Batch 1
11         N12   obob    Veh_PF   Day5      2021.12.14     2022.06.23  Batch 2
12         N13   obob    Veh_PF   Day5      2021.12.14     2022.06.24  Batch 3
13         N23   obob    Veh_PF   Day5      2021.12.14     2022.06.24  Batch 3
14         M13   obob      FGF1  Day14      2022.04.07     2022.06.22  Batch 1
15         M23   obob      FGF1  Day14      2022.04.06     2022.06.23  Batch 2
16         M27   obob      FGF1  Day14      2022.04.06     2022.06.23  Batch 2
17         M28   obob      FGF1  Day14      2022.04.06     2022.06.24  Batch 3
18         J11   obob      FGF1  Day14      2022.01.31     2022.06.22  Batch 1
19         J16   obob      FGF1  Day14      2022.01.31     2022.06.23  Batch 2
20         J18   obob      FGF1  Day14      2022.01.31     2022.06.24  Batch 3
21         M24   obob    Veh_PF  Day14      2022.04.07     2022.06.22  Batch 1
22         M25   obob    Veh_PF  Day14      2022.04.07     2022.06.23  Batch 2
23         M29   obob    Veh_PF  Day14      2022.04.07     2022.06.23  Batch 2
24         M30   obob    Veh_PF  Day14      2022.04.07     2022.06.24  Batch 3
25          J2   obob    Veh_PF  Day14      2022.02.01     2022.06.22  Batch 1
26          J7   obob    Veh_PF  Day14      2022.02.01     2022.06.23  Batch 2
27         J10   obob    Veh_PF  Day14      2022.02.01     2022.06.24  Batch 3
28          M2    BL6    Veh_PF   Day5      2022.03.29     2022.06.22  Batch 1
29          M4    BL6    Veh_PF   Day5      2022.03.29     2022.06.22  Batch 1
30          M5    BL6    Veh_PF   Day5      2022.03.29     2022.06.23  Batch 2
31          M6    BL6    Veh_PF   Day5      2022.03.29     2022.06.24  Batch 3
32         M17    BL6    Veh_PF  Day14      2022.04.07     2022.06.22  Batch 1
33         M18    BL6    Veh_PF  Day14      2022.04.07     2022.06.22  Batch 1
34         M19    BL6    Veh_PF  Day14      2022.04.07     2022.06.23  Batch 2
35         M20    BL6    Veh_PF  Day14      2022.04.07     2022.06.24  Batch 3

In [6]:
metadata_new_path = Path(project_dir, 'data/meta/metadata.csv')
os.makedirs(metadata_new_path.parent, exist_ok=True)

In [7]:
meta.to_csv(metadata_new_path, index=False)